<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:data.linz.govt.nz="http://data.linz.govt.nz" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://data.linz.govt.nz">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://data.linz.govt.nz/services;key=LINZ_LDS_API_KEY_REDACTED/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="layer-123109Type">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="road_section_id" nillable="true" type="xsd:int"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="road_id" nillable="true" type="xsd:int"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="full_road_name" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="road_name_label" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="road_name_body" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="road_name_type" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="road_name_suffix" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="secondary_road_name" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="tertiary_road_name" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="suburb_locality" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="town_city" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="territorial_authority" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="is_land" nillable="true" type="xsd:boolean"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="full_road_name_ascii" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="road_name_label_ascii" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="road_name_body_ascii" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="secondary_road_name_ascii" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="tertiary_road_name_ascii" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="suburb_locality_ascii" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="town_city_ascii" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="territorial_authority_ascii" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="shape" nillable="true" type="gml:CurvePropertyType"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="layer-123109" substitutionGroup="gml:AbstractFeature" type="data.linz.govt.nz:layer-123109Type"/>
</xsd:schema>
