-- 010: mark counterfactual snapshots transient, so they can never be served.
--
-- THE DEFECT THIS CLOSES
-- ----------------------
-- A bounded counterfactual copy is inserted into `network_snapshots` like any
-- other snapshot, and it inherits the source's `status = 'complete'` and
-- `coverage_kind = 'national'`. `api.snapshot_id()` picks the newest complete
-- national snapshot. So while a counterfactual copy exists - a network of
-- about 800 links covering 5 km of one district - it is a candidate to become
-- the application's automatically selected snapshot, and being newest, it wins.
--
-- A user would then be served a seven-hundred-link fragment presented as the
-- New Zealand road network. Every closure outside the fragment would report
-- DISCONNECTED. That is a considerably worse defect than anything this branch
-- has fixed, and it would appear and vanish depending on whether somebody
-- happened to be running an analysis.
--
-- Two independent guards, because either alone is one edit away from being
-- undone:
--
--   1. `is_transient` - an explicit flag that every automatic selection query
--      must exclude. Named for what it means rather than for what created it.
--   2. `coverage_kind = 'counterfactual'` - not one of the values any
--      selection query looks for, so a query that forgets guard 1 still does
--      not match.

ALTER TABLE network_snapshots
    ADD COLUMN IF NOT EXISTS is_transient boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN network_snapshots.is_transient IS
    'A working copy - a bounded counterfactual neighbourhood, or a what-if '
    'edit - that exists only for the duration of one analysis. NEVER a '
    'published answer, never automatically selected, and dropped when the '
    'analysis finishes or fails. Any query that chooses a snapshot on the '
    'user''s behalf must exclude these.';

-- Anything already created by the counterfactual machinery is transient by
-- definition. Retro-marking is safe: the id prefix is generated by this
-- codebase and nothing else uses it.
UPDATE network_snapshots
   SET is_transient = true
 WHERE snapshot_id LIKE 'cf-%' AND is_transient = false;

-- Partial index: the interesting question is almost always "which snapshots
-- are real", and transient rows should not slow that down.
CREATE INDEX IF NOT EXISTS network_snapshots_servable_idx
    ON network_snapshots (retrieved_at_utc DESC)
    WHERE is_transient = false;

-- Cleanup support. A crashed process leaves its copy behind, and without a
-- timestamp there is no safe way to tell an orphan from one in use.
ALTER TABLE network_snapshots
    ADD COLUMN IF NOT EXISTS transient_created_at timestamptz;

COMMENT ON COLUMN network_snapshots.transient_created_at IS
    'When a transient copy was made, so orphans left by a crashed process can '
    'be swept without touching one an analysis is still using.';
